[project]
name = "genai-accelerator-labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docling>=2.28.4",
    "fastapi>=0.115.12",
    "instructor>=1.7.7",
    "ipykernel>=6.29.5",
    "lancedb>=0.21.2",
    "openai>=1.69.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.0",
    "sqlalchemy>=2.0.40",
    "tiktoken>=0.9.0",
    "uvicorn>=0.34.0",
]
