name: genai-accelerator
services:
  db:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=aidb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
